# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_memo(object):
    def setupUi(self, Form_memo):
        Form_memo.setObjectName("Form_memo")
        Form_memo.resize(782, 303)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form_memo.sizePolicy().hasHeightForWidth())
        Form_memo.setSizePolicy(sizePolicy)
        Form_memo.setMinimumSize(QtCore.QSize(782, 303))
        Form_memo.setMaximumSize(QtCore.QSize(782, 303))
        self.plainTextEdit_text_input = QtWidgets.QPlainTextEdit(Form_memo)
        self.plainTextEdit_text_input.setGeometry(QtCore.QRect(0, 40, 381, 191))
        self.plainTextEdit_text_input.setObjectName("plainTextEdit_text_input")
        self.label = QtWidgets.QLabel(Form_memo)
        self.label.setGeometry(QtCore.QRect(0, 20, 101, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form_memo)
        self.label_2.setGeometry(QtCore.QRect(400, 20, 67, 17))
        self.label_2.setObjectName("label_2")
        self.pushButton_extract = QtWidgets.QPushButton(Form_memo)
        self.pushButton_extract.setGeometry(QtCore.QRect(690, 240, 89, 25))
        self.pushButton_extract.setObjectName("pushButton_extract")
        self.pushButton_clearall = QtWidgets.QPushButton(Form_memo)
        self.pushButton_clearall.setGeometry(QtCore.QRect(690, 270, 89, 25))
        self.pushButton_clearall.setObjectName("pushButton_clearall")
        self.listView_list_output = QtWidgets.QListView(Form_memo)
        self.listView_list_output.setGeometry(QtCore.QRect(400, 40, 381, 191))
        self.listView_list_output.setObjectName("listView_list_output")
        self.label_3 = QtWidgets.QLabel(Form_memo)
        self.label_3.setGeometry(QtCore.QRect(10, 240, 31, 17))
        self.label_3.setObjectName("label_3")
        self.lineEdit_key = QtWidgets.QLineEdit(Form_memo)
        self.lineEdit_key.setGeometry(QtCore.QRect(40, 240, 341, 25))
        self.lineEdit_key.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.lineEdit_key.setObjectName("lineEdit_key")
        self.pushButton_audio_input = QtWidgets.QPushButton(Form_memo)
        self.pushButton_audio_input.setGeometry(QtCore.QRect(590, 270, 89, 25))
        self.pushButton_audio_input.setObjectName("pushButton_audio_input")

        self.retranslateUi(Form_memo)
        QtCore.QMetaObject.connectSlotsByName(Form_memo)

    def retranslateUi(self, Form_memo):
        _translate = QtCore.QCoreApplication.translate
        Form_memo.setWindowTitle(_translate("Form_memo", "智能备忘录"))
        self.label.setText(_translate("Form_memo", "输入"))
        self.label_2.setText(_translate("Form_memo", "输出"))
        self.pushButton_extract.setText(_translate("Form_memo", "提取"))
        self.pushButton_clearall.setText(_translate("Form_memo", "清空"))
        self.label_3.setText(_translate("Form_memo", "key:"))
        self.pushButton_audio_input.setText(_translate("Form_memo", "语音输入"))
